#! /bin/bash

currentChangesetPhase=`hg log -r ". and secret()" --template {node}`

if [ "$currentChangesetPhase" != "" ] ; then
  echo "Cannot merge onto changeset that is in secret phase."
  echo "    See hg help phases"
  echo ""
  exit 1
fi
