#! /bin/bash

updatedChangesetPhase=`hg log -r "matching(.)::secret()" --template {node}`

if [ "$updatedChangesetPhase" != "" ] ; then
  echo "Cannot merge onto changeset that is in secret phase."
  echo "    See hg help phases"
  echo ""
  exit 1
fi
